version: "3"
networks:
  app:
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=instateam
      - POSTGRES_USER=instateam
      - POSTGRES_PASSWORD=instateam
    networks:
      - app
