# Generated by Django 5.0.2 on 2024-02-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="team",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
